# Generated by Django 4.2.6 on 2024-03-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rental_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="book",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
